name: Directory Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test
      working-directory: directory-structure/hashlib
      run: ls /home/runner/work/fluent-c/fluent-c/directory-structure/hashlib/inc
      
    - name: Build hashlib    
      working-directory: directory-structure/hashlib
      run: make

    - name: test step
      working-directory: ifdef
      run: ls
