name: ifdef Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build ifdef Linux    
      working-directory: ifdef
      run: make

    - name: Run ifdef Linux
      working-directory: ifdef
      run: ./ifdef

    - name: Show file content
      working-directory: ifdef
      run: cat ./newdir/newfile
