name: Lifetime and Ownership

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build driver  
      working-directory: lifetime-ownership
      run: make

    - name: Run driver application
      working-directory: lifetime-ownership
      run: ./driver
      
