name: Pattern Story - Logger Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build application    
      working-directory: pattern-story-logger
      run: make

    - name: Run application
      working-directory: pattern-story-logger
      run: ./logger

    - name: Show logfile content
      working-directory: pattern-story-logger
      run: more log.txt
