name: Returning Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build application    
      working-directory: returning-data
      run: make

    - name: Run application
      working-directory: returning-data
      run: ./returndata
